services:
  # Job Producer (API) Service
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: webhook-api
    env_file:
      - .docker.env
    ports:
      - "8000:7000"

    networks:
      - webhook-network
    restart: unless-stopped

  # Worker Service
  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: webhook-worker
    env_file:
      - .docker.env

    networks:
      - webhook-network
    restart: unless-stopped

  # Dashboard Service
  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    container_name: webhook-dashboard
    env_file:
      - .docker.env
    ports:
      - "8001:7001"

    networks:
      - webhook-network
    restart: unless-stopped

networks:
  webhook-network:
    driver: bridge
